### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by nougator**

### CODE REVIEW

**Review by nobody5050 — CHANGES_REQUESTED** [review]
The copyright text change is unnecessary but ok

**Comment by nougator** [comment]
Done

**Review by Alvarito050506 — COMMENTED** [review]
Hello!

The changes in the `launcher.html` file just "drop" the ability to view and edit the page locally, without a web server. And, to be honest, I don't like the visual changes. But you should talk to @MFDGaming about it.

**Comment by Alvarito050506** [comment]
Closed due to inactivity.

**Pull request closed without merging**
